version = 0.1

[default.deploy.parameters]
stack_name = "feelink-stack"
resolve_s3 = true
s3_prefix = "feelink-stack"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
