AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Feelink backend (Lambda + DynamoDB + HTTP API)

Globals:
  Function:
    Timeout: 10
    Runtime: nodejs20.x

Resources:
  FeelinkTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: sessionId
          AttributeType: S
      KeySchema:
        - AttributeName: sessionId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowHeaders:
          - content-type
        AllowMethods:
          - OPTIONS
          - POST

  ChatFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/app.handler
      CodeUri: .
      Environment:
        Variables:
          SESSIONS_TABLE: !Ref FeelinkTable
          ACTIVITIES_TABLE: ActivitiesEncourageFeelink
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FeelinkTable
        - Statement:
            - Sid: ActivitiesRead
              Effect: Allow
              Action:
                - dynamodb:DescribeTable
                - dynamodb:Scan
                - dynamodb:Query
                - dynamodb:GetItem
              Resource: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/ActivitiesEncourageFeelink
      Events:
        ChatApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /chat
            Method: post

Outputs:
  HttpApiUrl:
    Description: "HTTP API URL"
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com" 